# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fya5Iy3YRyo68lExgYKw4_QflXtaf6JH
"""

from google.colab import files
uploaded = files.upload()

# Install required libraries (run once)
!pip install xgboost shap

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, classification_report,
    ConfusionMatrixDisplay, RocCurveDisplay
)

# Try loading optional libraries
try:
    from xgboost import XGBClassifier
    xgbavailable1 = True
except:
    xgbavailable1 = False

try:
    import shap
    shapavailable1 = True
except:
    shapavailable1 = False


# Upload dataset from your system
uploaded = files.upload()
df = pd.read_csv("heart_disease_uci.csv")

print("Dataset loaded:", df.shape)
display(df.head())


# Clean column names for consistency
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

print("Columns:", df.columns.tolist())


# Quick data check
print(df.info())
print(df.isnull().sum())


# Automatically detect target column
possible_targets1 = ["target", "num", "output", "label", "condition"]
targetcol = next((col for col in possible_targets1 if col in df.columns), None)

if targetcol is None:
    raise ValueError("Target column not found")

print("Target column:", target_col)


# Convert target to binary if needed
if df[targetcol].nunique() > 2:
    df[targetcol] = df[targetcol].apply(lambda x: 0 if x == 0 else 1)


# Split features and label
X = df.drop(columns=[targetcol])
y = df[targetcol]


# Encode categorical columns
categorical_cols = X.select_dtypes(include=["object"]).columns.tolist()
numeric_cols = X.select_dtypes(exclude=["object"]).columns.tolist()

for col in categorical_cols:
    X[col] = LabelEncoder().fit_transform(X[col].astype(str))


# Build preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        ("num", Pipeline([
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler())
        ]), numeric_cols)
    ]
)


# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


# Define models
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(n_estimators=200),
    "SVM": SVC(probability=True),
    "KNN": KNeighborsClassifier()
}

if xgbavailable1:
    models["XGBoost"] = XGBClassifier(eval_metric="logloss")


# Train and evaluate each model
results = {}
trained_models = {}

for name, model in models.items():
    print(f"\nModel: {name}")

    pipe = Pipeline([
        ("prep", preprocessor),
        ("model", model)
    ])

    pipe.fit(X_train, y_train)
    trained_models[name] = pipe

    y_pred = pipe.predict(X_test)
    y_prob = pipe.predict_proba(X_test)[:, 1]

    print("Accuracy :", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred))
    print("Recall   :", recall_score(y_test, y_pred))
    print("F1 Score :", f1_score(y_test, y_pred))
    print("ROC-AUC  :", roc_auc_score(y_test, y_prob))

    print("\nReport:")
    print(classification_report(y_test, y_pred))

    ConfusionMatrixDisplay.from_predictions(y_test, y_pred)
    plt.title(name)
    plt.show()

    RocCurveDisplay.from_predictions(y_test, y_prob)
    plt.title(name)
    plt.show()

    results[name] = recall_score(y_test, y_pred)


# Pick best model based on recall
best_model_name = max(results, key=results.get)
best_model = trained_models[best_model_name]

print("\nBest model:", best_model_name)


# Feature importance (for tree models)
model_only = best_model.named_steps["model"]
preprocessor = best_model.named_steps["prep"]

if hasattr(model_only, "feature_importances_"):

    try:
        feature_names = preprocessor.get_feature_names_out()
    except:
        feature_names = X.columns

    importances = model_only.feature_importances_

    if len(feature_names) != len(importances):
        min_len = min(len(feature_names), len(importances))
        feature_names = feature_names[:min_len]
        importances = importances[:min_len]

    importance_df = pd.DataFrame({
        "Feature": feature_names,
        "Importance": importances
    }).sort_values(by="Importance", ascending=False)

    display(importance_df)

    plt.figure(figsize=(10, 6))
    plt.barh(importance_df["Feature"], importance_df["Importance"])
    plt.gca().invert_yaxis()
    plt.title("Feature Importance")
    plt.show()

else:
    print("Feature importance not available for this model")


# SHAP explanation (only for tree models)
if shapavailable1 and hasattr(model_only, "feature_importances_"):

    X_processed = best_model.named_steps["prep"].transform(X_test)

    explainer = shap.TreeExplainer(model_only)
    shap_values = explainer.shap_values(X_processed)

    shap.summary_plot(shap_values, X_processed, feature_names=X.columns)


# Try a sample prediction
sample = pd.DataFrame([X.median()])

pred = best_model.predict(sample)[0]
prob = best_model.predict_proba(sample)[0][1]

print("\nPrediction:", "Disease" if pred == 1 else "No Disease")
print("Probability:", prob)